version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - DATABASE_URI=mongodb://db/contests
      - OWNER_ID=$OWNER_ID
      - GUILD_ID=$GUILD_ID
      - ADMIN_ROLES=$ADMIN_ROLES
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:dcef38a5b82ca7e1293055ededc22d38fb27fffb526523c70a4cbd864182c310
    restart: always
    volumes:
      - ./database:/data/db
