version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - DATABASE_URI=mongodb://db/contests
      - OWNER_ID=$OWNER_ID
      - GUILD_ID=$GUILD_ID
      - ADMIN_ROLES=$ADMIN_ROLES
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:5f3066565902a2221ad529ba4f7f8ee5ee386156caffb72ff28a779c6da8a598
    restart: always
    volumes:
      - ./database:/data/db
