version: '3.3'

services:
  contests:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://mongo/contests
    volumes:
      - ./logs:/app/logs
  mongo:
    image: mongo:5@sha256:784609d84706ee289f74eb8b7dd5821ec2f85c9b51312503d46cf748d0cb6dab
    restart: always
    volumes:
      - ./data:/data/db