version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://db/contests
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:81c73ed6f9d083c65199fe71aae0302b3643128efd99e00e1096651952d661b0
    restart: always
    volumes:
      - ./database:/data/db