version: '3.3'

services:
  contests:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://mongo/contests
    volumes:
      - ./logs:/app/logs
  mongo:
    image: mongo:5@sha256:82302b06360729842acd27ab8a91c90e244f17e464fcfd366b7427af652c5559
    restart: always
    volumes:
      - ./data:/data/db