version: '3.3'

services:
  contests:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://mongo/contests
    volumes:
      - ./logs:/app/logs
  mongo:
    image: mongo:5@sha256:ff4050d808f943c0835c0aa24cce07afd86193253713020ca399a2b6c7840a03
    restart: always
    volumes:
      - ./data:/data/db