version: '3.3'

services:
  contests:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://mongo/contests
    volumes:
      - ./logs:/app/logs
  mongo:
    image: mongo:5@sha256:a9775b8686e8c5c298712ae1eea710bb341ffbb3f306dd7681f60c5b8d7fae90
    restart: always
    volumes:
      - ./data:/data/db