version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - DATABASE_URI=mongodb://db/contests
      - OWNER_ID=$OWNER_ID
      - GUILD_ID=$GUILD_ID
      - ADMIN_ROLES=$ADMIN_ROLES
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:033255f596fb18ee947fabef1377f666f96ff0c0328242a7ff219c284537a76f
    restart: always
    volumes:
      - ./database:/data/db
