version: '3.3'

services:
  contests:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://mongo/contests
    volumes:
      - ./logs:/app/logs
  mongo:
    image: mongo:5@sha256:1cc0e2edb2be9e1e05bb822346a86bc5946cee73e301c14543adf9d89dbf0ff0
    restart: always
    volumes:
      - ./data:/data/db