version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://db/contests
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:6be4995a52c8ee8ec1170477518a68c91b1a4259a5da90a7d08408f373accabb
    restart: always
    volumes:
      - ./database:/data/db