version: '3.3'

services:
  contests:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://mongo/contests
    volumes:
      - ./logs:/app/logs
  mongo:
    image: mongo:5@sha256:ef401891b08d39656c317016c29b8a190e5a05570b661b303944eda892824e85
    restart: always
    volumes:
      - ./data:/data/db