version: '3.3'

services:
  contests:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://mongo/contests
    volumes:
      - ./logs:/app/logs
  mongo:
    image: mongo:5@sha256:5cf2743719c65e596ed585447261428ebfe5b6e8c4402ea1f02d593222493c6a
    restart: always
    volumes:
      - ./data:/data/db