version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - DATABASE_URI=mongodb://db/contests
      - OWNER_ID=$OWNER_ID
      - GUILD_ID=$GUILD_ID
      - ADMIN_ROLES=$ADMIN_ROLES
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:4c87569cd32d72a4452119eada42236d1b14231916a6520b96c8521dc3e09c8a
    restart: always
    volumes:
      - ./database:/data/db
