version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://db/contests
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:493ad22eafd5d4f43c19ec0041932282b829a48a04b7295b89238f1022b1a194
    restart: always
    volumes:
      - ./database:/data/db