version: '3.3'

services:
  contests:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://mongo/contests
    volumes:
      - ./logs:/app/logs
  mongo:
    image: mongo:5@sha256:4200c3073389d5b303070e53ff8f5e4472efb534340d28599458ccc24f378025
    restart: always
    volumes:
      - ./data:/data/db