version: '3.3'

services:
  contests:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://mongo/contests
    volumes:
      - ./logs:/app/logs
  mongo:
    image: mongo:5@sha256:58f91b0abfc7d84728f63faa215328bd6cda6392ac65c7b1c1e38886aa89133f
    restart: always
    volumes:
      - ./data:/data/db