version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - DATABASE_URI=mongodb://db/contests
      - OWNER_ID=$OWNER_ID
      - GUILD_ID=$GUILD_ID
      - ADMIN_ROLES=$ADMIN_ROLES
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:dd66acbd358b4b238336101f122bae368421069274e14233a9abb4f166ed4130
    restart: always
    volumes:
      - ./database:/data/db
