version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://db/contests
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:f036720ff82f8739412f0915a84d6d5dfa9020106f73471a49838ac810cf56fa
    restart: always
    volumes:
      - ./database:/data/db