version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://db/contests
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:fa05be0d090caa8d18da38313c90019b86546bb4a0d029d45c0a175b5ce3a3e4
    restart: always
    volumes:
      - ./database:/data/db