version: '3.3'

services:
  contests:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://mongo/contests
    volumes:
      - ./logs:/app/logs
  mongo:
    image: mongo:5@sha256:90c1af2335fc7570e3c81690c22d3cea62f855e3f9a79f4f5299b736c3803d2a
    restart: always
    volumes:
      - ./data:/data/db