name: Docker Compose

on:
  push:
  pull_request:

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2

    - name: Test docker compose build
      run: docker compose build