name: Docker Compose

on:
  push:
  pull_request:

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

    - name: Test docker compose build
      run: docker compose build